/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/laybson/compiladores/Projeto-Compilador-C/c.lex</tt>
 */
public class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\52\1\2\1\53\1\54\1\1\22\0\1\52\1\41\1\55"+
    "\2\0\1\41\1\44\1\57\1\40\1\40\1\42\1\41\1\40\1\35"+
    "\1\36\1\43\1\37\11\34\1\0\1\40\1\47\1\46\1\50\2\0"+
    "\32\33\1\40\1\56\1\40\1\41\1\33\1\0\1\3\1\10\1\17"+
    "\1\7\1\12\1\20\1\22\1\21\1\13\1\33\1\23\1\11\1\26"+
    "\1\14\1\6\1\30\1\33\1\16\1\15\1\5\1\4\1\25\1\24"+
    "\1\32\1\27\1\31\1\40\1\45\1\40\1\51\6\0\1\53\u1fa2\0"+
    "\1\53\1\53\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\20\3\1\4\1\5\1\4\1\6"+
    "\7\5\2\1\3\3\1\7\7\3\1\7\13\3\2\0"+
    "\1\10\1\0\1\2\1\0\1\11\3\0\1\12\30\3"+
    "\1\13\1\14\2\0\16\3\1\0\11\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\60\0\220\0\300\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0"+
    "\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\60"+
    "\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0510\0\60\0\u0540"+
    "\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0"+
    "\0\u06f0\0\u0720\0\u0750\0\u0780\0\u0120\0\u07b0\0\u07e0\0\u0810"+
    "\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990"+
    "\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0540\0\60\0\u0ab0"+
    "\0\u0570\0\u0ae0\0\u0570\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0"+
    "\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50"+
    "\0\u0d80\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0"+
    "\0\u0f00\0\u0f30\0\u0f60\0\u09c0\0\u09f0\0\u0f90\0\u0fc0\0\u0ff0"+
    "\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140\0\u1170"+
    "\0\u11a0\0\u11d0\0\u1200\0\u1230\0\u1260\0\u1290\0\u12c0\0\u12f0"+
    "\0\u1320\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410\0\u1440";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\10\1\16\1\17\1\20"+
    "\1\21\1\10\1\22\1\10\1\23\1\24\6\10\1\25"+
    "\1\26\1\2\1\27\1\30\2\31\1\32\1\33\1\34"+
    "\1\31\1\35\1\36\1\37\1\4\1\0\1\4\1\40"+
    "\1\2\1\41\62\0\1\4\60\0\1\10\1\42\30\10"+
    "\2\0\1\10\23\0\11\10\1\43\20\10\2\0\1\10"+
    "\23\0\24\10\1\44\5\10\2\0\1\10\23\0\32\10"+
    "\2\0\1\10\23\0\3\10\1\45\3\10\1\46\22\10"+
    "\2\0\1\10\23\0\13\10\1\47\16\10\2\0\1\10"+
    "\23\0\3\10\1\50\26\10\2\0\1\10\23\0\6\10"+
    "\1\51\2\10\1\52\15\10\1\53\2\10\2\0\1\10"+
    "\23\0\11\10\1\54\3\10\1\55\14\10\2\0\1\10"+
    "\23\0\2\10\1\56\5\10\1\57\5\10\1\60\2\10"+
    "\1\61\10\10\2\0\1\10\23\0\7\10\1\62\22\10"+
    "\2\0\1\10\23\0\1\51\2\10\1\63\12\10\1\64"+
    "\13\10\2\0\1\10\23\0\3\10\1\65\2\10\1\66"+
    "\23\10\2\0\1\10\23\0\3\10\1\42\26\10\2\0"+
    "\1\10\23\0\16\10\1\67\13\10\2\0\1\10\23\0"+
    "\3\10\1\70\26\10\2\0\1\10\54\0\1\25\1\0"+
    "\1\71\1\25\54\0\1\25\2\0\1\27\6\0\1\37"+
    "\43\0\1\72\1\0\1\73\1\0\1\71\1\73\66\0"+
    "\1\37\53\0\1\74\1\75\2\0\1\37\55\0\1\37"+
    "\1\0\1\37\56\0\1\37\60\0\2\37\56\0\1\37"+
    "\1\0\1\37\7\0\55\76\1\77\1\100\1\76\55\101"+
    "\1\0\1\102\1\103\3\0\2\10\1\104\27\10\2\0"+
    "\1\10\23\0\10\10\1\105\1\10\1\106\17\10\2\0"+
    "\1\10\23\0\25\10\1\107\4\10\2\0\1\10\23\0"+
    "\1\10\1\110\30\10\2\0\1\10\23\0\15\10\1\111"+
    "\14\10\2\0\1\10\23\0\7\10\1\112\22\10\2\0"+
    "\1\10\23\0\11\10\1\113\20\10\2\0\1\10\23\0"+
    "\12\10\1\114\17\10\2\0\1\10\23\0\1\10\1\115"+
    "\30\10\2\0\1\10\23\0\2\10\1\116\27\10\2\0"+
    "\1\10\23\0\2\10\1\55\27\10\2\0\1\10\23\0"+
    "\1\117\12\10\1\120\16\10\2\0\1\10\23\0\17\10"+
    "\1\121\6\10\1\122\3\10\2\0\1\10\23\0\3\10"+
    "\1\123\26\10\2\0\1\10\23\0\10\10\1\124\21\10"+
    "\2\0\1\10\23\0\2\10\1\125\14\10\1\126\12\10"+
    "\2\0\1\10\23\0\11\10\1\127\20\10\2\0\1\10"+
    "\23\0\1\65\31\10\2\0\1\10\23\0\13\10\1\55"+
    "\16\10\2\0\1\10\23\0\3\10\1\130\26\10\2\0"+
    "\1\10\23\0\10\10\1\131\21\10\2\0\1\10\23\0"+
    "\6\10\1\132\1\10\1\133\21\10\2\0\1\10\54\0"+
    "\1\134\2\0\1\134\54\0\1\135\2\0\1\135\54\0"+
    "\1\73\1\0\1\71\1\73\20\0\42\136\1\137\15\136"+
    "\1\75\1\3\1\4\55\75\1\76\2\0\50\76\2\0"+
    "\3\76\1\101\2\0\50\101\2\0\3\101\3\0\3\10"+
    "\1\55\26\10\2\0\1\10\23\0\3\10\1\140\26\10"+
    "\2\0\1\10\23\0\10\10\1\141\21\10\2\0\1\10"+
    "\23\0\7\10\1\142\22\10\2\0\1\10\23\0\5\10"+
    "\1\131\24\10\2\0\1\10\23\0\1\143\31\10\2\0"+
    "\1\10\23\0\1\144\31\10\2\0\1\10\23\0\17\10"+
    "\1\55\12\10\2\0\1\10\23\0\7\10\1\55\22\10"+
    "\2\0\1\10\23\0\23\10\1\55\6\10\2\0\1\10"+
    "\23\0\7\10\1\145\22\10\2\0\1\10\23\0\2\10"+
    "\1\146\27\10\2\0\1\10\23\0\1\10\1\147\30\10"+
    "\2\0\1\10\23\0\11\10\1\150\20\10\2\0\1\10"+
    "\23\0\7\10\1\151\22\10\2\0\1\10\23\0\13\10"+
    "\1\54\16\10\2\0\1\10\23\0\2\10\1\152\27\10"+
    "\2\0\1\10\23\0\1\10\1\145\30\10\2\0\1\10"+
    "\23\0\10\10\1\153\21\10\2\0\1\10\23\0\2\10"+
    "\1\154\7\10\1\54\17\10\2\0\1\10\23\0\1\54"+
    "\31\10\2\0\1\10\23\0\6\10\1\114\23\10\2\0"+
    "\1\10\23\0\1\155\31\10\2\0\1\10\23\0\4\10"+
    "\1\55\25\10\2\0\1\10\20\0\42\136\1\156\15\136"+
    "\42\0\1\137\1\4\17\0\11\10\1\55\20\10\2\0"+
    "\1\10\23\0\17\10\1\121\12\10\2\0\1\10\23\0"+
    "\4\10\1\157\25\10\2\0\1\10\23\0\1\10\1\160"+
    "\30\10\2\0\1\10\23\0\20\10\1\55\11\10\2\0"+
    "\1\10\23\0\13\10\1\140\16\10\2\0\1\10\23\0"+
    "\10\10\1\161\21\10\2\0\1\10\23\0\14\10\1\54"+
    "\15\10\2\0\1\10\23\0\7\10\1\133\22\10\2\0"+
    "\1\10\23\0\3\10\1\162\26\10\2\0\1\10\23\0"+
    "\14\10\1\163\15\10\2\0\1\10\23\0\12\10\1\164"+
    "\17\10\2\0\1\10\23\0\10\10\1\165\21\10\2\0"+
    "\1\10\23\0\2\10\1\67\27\10\2\0\1\10\20\0"+
    "\42\136\1\156\1\4\14\136\3\0\7\10\1\162\22\10"+
    "\2\0\1\10\23\0\6\10\1\54\23\10\2\0\1\10"+
    "\23\0\14\10\1\55\15\10\2\0\1\10\23\0\15\10"+
    "\1\55\14\10\2\0\1\10\23\0\16\10\1\55\13\10"+
    "\2\0\1\10\23\0\2\10\1\166\27\10\2\0\1\10"+
    "\23\0\11\10\1\167\20\10\2\0\1\10\23\0\7\10"+
    "\1\65\22\10\2\0\1\10\23\0\1\10\1\114\30\10"+
    "\2\0\1\10\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5232];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\23\1\1\11\6\1\1\11"+
    "\31\1\2\0\1\1\1\0\1\1\1\0\1\11\3\0"+
    "\33\1\2\0\16\1\1\0\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */


private CToken createToken(String name, String value) {
    return new CToken( name, value, yyline, yycolumn);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public CToken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Caractere inválido " + yytext() + " na linha " + yyline + ", coluna " +yycolumn);
            }
          case 13: break;
          case 2: 
            { /**/
            }
          case 14: break;
          case 3: 
            { return createToken("Identifier", yytext());
            }
          case 15: break;
          case 4: 
            { return createToken("Integer", yytext());
            }
          case 16: break;
          case 5: 
            { return createToken("Operator", yytext());
            }
          case 17: break;
          case 6: 
            { return createToken("Separator", yytext());
            }
          case 18: break;
          case 7: 
            { return createToken("Keyword", yytext());
            }
          case 19: break;
          case 8: 
            { return createToken("Octal", yytext());
            }
          case 20: break;
          case 9: 
            { return createToken("String", yytext());
            }
          case 21: break;
          case 10: 
            { return createToken("Char", yytext());
            }
          case 22: break;
          case 11: 
            { return createToken("Float", yytext());
            }
          case 23: break;
          case 12: 
            { return createToken("Hexadecimal", yytext());
            }
          case 24: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
