
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SHORT = 42;
  public static final int INTER = 65;
  public static final int SIGNED = 45;
  public static final int LEFT_ASSIGN = 24;
  public static final int IDENTIFIER = 2;
  public static final int BOOL = 40;
  public static final int MOD_ASSIGN = 21;
  public static final int OR_OP = 18;
  public static final int GT = 57;
  public static final int ENUMERATION_CONSTANT = 30;
  public static final int SUB_ASSIGN = 23;
  public static final int AND_OP = 17;
  public static final int CONST = 37;
  public static final int TIL = 62;
  public static final int RKEY = 74;
  public static final int REGISTER = 35;
  public static final int ENUM = 54;
  public static final int IMAGINARY = 51;
  public static final int SIZEOF = 7;
  public static final int INC_OP = 9;
  public static final int COMMA = 68;
  public static final int GE_OP = 14;
  public static final int RPAREN = 67;
  public static final int DEC_OP = 10;
  public static final int AND_ASSIGN = 26;
  public static final int LT = 56;
  public static final int FUNC_NAME = 6;
  public static final int DOUBLE = 48;
  public static final int STRUCT = 52;
  public static final int LE_OP = 13;
  public static final int LPAREN = 66;
  public static final int PERC = 78;
  public static final int LBRA = 71;
  public static final int XOR_ASSIGN = 27;
  public static final int INLINE = 36;
  public static final int FLOAT = 47;
  public static final int GOTO = 88;
  public static final int F_CONSTANT = 4;
  public static final int DDOT = 61;
  public static final int RIGHT_ASSIGN = 25;
  public static final int GENERIC = 95;
  public static final int RBRA = 72;
  public static final int PIPE = 59;
  public static final int ADD_ASSIGN = 22;
  public static final int LONG = 44;
  public static final int PLUS = 69;
  public static final int WHILE = 85;
  public static final int UNION = 53;
  public static final int MUL_ASSIGN = 19;
  public static final int TYPEDEF_NAME = 29;
  public static final int CHAR = 41;
  public static final int EXCLA = 79;
  public static final int PTR_OP = 8;
  public static final int SWITCH = 84;
  public static final int FOR = 87;
  public static final int DO = 86;
  public static final int STAR = 76;
  public static final int VOID = 49;
  public static final int EXTERN = 32;
  public static final int RETURN = 91;
  public static final int ELSE = 83;
  public static final int RESTRICT = 38;
  public static final int BREAK = 90;
  public static final int DOT = 60;
  public static final int INT = 43;
  public static final int STRING_LITERAL = 5;
  public static final int SEMICOLON = 75;
  public static final int EOF = 0;
  public static final int DEFAULT = 81;
  public static final int MINUS = 70;
  public static final int error = 1;
  public static final int RIGHT_OP = 12;
  public static final int OR_ASSIGN = 28;
  public static final int ALIGNOF = 93;
  public static final int CONTINUE = 89;
  public static final int IF = 82;
  public static final int UNSIGNED = 46;
  public static final int DIV_ASSIGN = 20;
  public static final int ATOMIC = 94;
  public static final int STATIC_ASSERT = 97;
  public static final int CARET = 63;
  public static final int NORETURN = 96;
  public static final int VOLATILE = 39;
  public static final int CASE = 80;
  public static final int NE_OP = 16;
  public static final int EQ_OP = 15;
  public static final int I_CONSTANT = 3;
  public static final int THREAD_LOCAL = 98;
  public static final int AND = 58;
  public static final int BAR = 77;
  public static final int COMPLEX = 50;
  public static final int ELLIPSIS = 55;
  public static final int STATIC = 33;
  public static final int LKEY = 73;
  public static final int TYPEDEF = 31;
  public static final int ALIGNAS = 92;
  public static final int AUTO = 34;
  public static final int LEFT_OP = 11;
  public static final int EQUALS = 64;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "I_CONSTANT",
  "F_CONSTANT",
  "STRING_LITERAL",
  "FUNC_NAME",
  "SIZEOF",
  "PTR_OP",
  "INC_OP",
  "DEC_OP",
  "LEFT_OP",
  "RIGHT_OP",
  "LE_OP",
  "GE_OP",
  "EQ_OP",
  "NE_OP",
  "AND_OP",
  "OR_OP",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "LEFT_ASSIGN",
  "RIGHT_ASSIGN",
  "AND_ASSIGN",
  "XOR_ASSIGN",
  "OR_ASSIGN",
  "TYPEDEF_NAME",
  "ENUMERATION_CONSTANT",
  "TYPEDEF",
  "EXTERN",
  "STATIC",
  "AUTO",
  "REGISTER",
  "INLINE",
  "CONST",
  "RESTRICT",
  "VOLATILE",
  "BOOL",
  "CHAR",
  "SHORT",
  "INT",
  "LONG",
  "SIGNED",
  "UNSIGNED",
  "FLOAT",
  "DOUBLE",
  "VOID",
  "COMPLEX",
  "IMAGINARY",
  "STRUCT",
  "UNION",
  "ENUM",
  "ELLIPSIS",
  "LT",
  "GT",
  "AND",
  "PIPE",
  "DOT",
  "DDOT",
  "TIL",
  "CARET",
  "EQUALS",
  "INTER",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "PLUS",
  "MINUS",
  "LBRA",
  "RBRA",
  "LKEY",
  "RKEY",
  "SEMICOLON",
  "STAR",
  "BAR",
  "PERC",
  "EXCLA",
  "CASE",
  "DEFAULT",
  "IF",
  "ELSE",
  "SWITCH",
  "WHILE",
  "DO",
  "FOR",
  "GOTO",
  "CONTINUE",
  "BREAK",
  "RETURN",
  "ALIGNAS",
  "ALIGNOF",
  "ATOMIC",
  "GENERIC",
  "NORETURN",
  "STATIC_ASSERT",
  "THREAD_LOCAL"
  };
}

